### ISSUE TITLE
[Question] Local environment readiness - Failing zksync redeploy

### ISSUE THREAD

**Issue by rrodriguezreche** [matter-labs/zksync#222]
Hi!

I am following the local dev environment instructions. I am trying to familiarize with how L2 implementations work and this one seems the friendliest of them all. That said, although there are pretty clear instructions about how to deploy a dev environment, I have been unable to do it.

There is a message `TODO: fix minikube local dev` when issuing `zksync redeploy`. That leads me to think that this is still work in progress. Am I wrong?

In any case, I will leave here my current issues if it were of any help:

- When firing `zksync redeploy` as per the instructions, I got the following error
```
TODO: fix minikube local dev
redeploying for the db postgres://postgres@localhost/plasma
make[1]: Entering directory '/home/mad/zksync'
make[1]: Leaving directory '/home/mad/zksync'
yarn run v1.21.1
warning package.json: No license field                                                                                                                        
$ yarn build && ts-node scripts/testnet-deploy.ts --deploy --publish
warning package.json: No license field                                                                                                                        
$ waffle config.json && waffle config_flat.json
contracts/Franklin.sol:196:9: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
        address _genesisAccAddress,
        ^------------------------^

contracts/Franklin.sol:697:47: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function verifyBlock(uint32 _blockNumber, uint256[8] calldata _proof)
                                              ^------------------------^

flat/Franklin.sol:1026:9: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
        address _genesisAccAddress,
        ^------------------------^

flat/Franklin.sol:1527:47: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function verifyBlock(uint32 _blockNumber, uint256[8] calldata _proof)
                                              ^------------------------^

Error: Cannot find module '../build/FranklinTest'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/mad/zksync/contracts/src.ts/deploy.ts:64:36)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Module.m._compile (/home/mad/zksync/contracts/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/mad/zksync/contracts/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/mad/zksync/contracts/scripts/testnet-deploy.ts:40:16)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Module.m._compile (/home/mad/zksync/contracts/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/mad/zksync/contracts/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
error Command failed with exit code 1.                                                                                                                        
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Contract deployment failed
Makefile:143: recipe for target 'deploy-contracts' failed
make: *** [deploy-contracts] Error 1
```

I managed to solve it by tinkering a bit with the src and found `prepare-test-contracts.sh`, which is not pointed in the instructions.

- After running the above mentioned script, the `zksync redeploy` command still gives me an error, which I am currently trying to troubleshoot (will update if I manage to get past it)

```
TODO: fix minikube local dev
redeploying for the db postgres://postgres@localhost/plasma
make[1]: Entering directory '/home/mad/zksync'
make[1]: Leaving directory '/home/mad/zksync'
yarn run v1.21.1
warning package.json: No license field                                                                                                                        
$ yarn build && ts-node scripts/testnet-deploy.ts --deploy --publish
warning package.json: No license field                                                                                                                        
$ waffle config.json && waffle config_flat.json
contracts/Franklin.sol:196:9: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
        address _genesisAccAddress,
        ^------------------------^

contracts/Franklin.sol:697:47: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function verifyBlock(uint32 _blockNumber, uint256[8] calldata _proof)
                                              ^------------------------^

contracts/generated/FranklinTest.sol:196:9: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
        address _genesisAccAddress,
        ^------------------------^

contracts/generated/FranklinTest.sol:697:47: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function verifyBlock(uint32 _blockNumber, uint256[8] calldata _proof)
                                              ^------------------------^

flat/Franklin.sol:1026:9: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
        address _genesisAccAddress,
        ^------------------------^

flat/Franklin.sol:1527:47: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function verifyBlock(uint32 _blockNumber, uint256[8] calldata _proof)
                                              ^------------------------^

GOVERNANCE_ADDR=0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9
PRIORITY_QUEUE_ADDR=0x572b9410D9a14Fa729F3af92cB83A07aaA472dE0
VERIFIER_ADDR=0xc56E79CAA94C96DE01eF36560ac215cC7A4F0F47
CONTRACT_ADDR=0x70a0F165d6f8054d0d0CF8dFd4DD2005f0AF6B55
TEST_ERC20=0x54FCb2405EE4f574C4F09333d25c401E68aD3408
Done in 36.77s.
CONTRACT_ADDR=0x70a0F165d6f8054d0d0CF8dFd4DD2005f0AF6B55
psql: FATAL:  database "plasma" does not exist
Makefile:45: recipe for target 'db-insert-contract' failed
make: *** [db-insert-contract] Error 1
```

Regards!

**Comment by furkhat** [comment]
Hi,
> psql: FATAL:  database "plasma" does not exist

This means database is not created. You probably forgot to do `zksync init`. That is required initial step to configure environment.

I just tested setup institutions on latest master from clean clone of the repo, seems to be no problem. Let me know if you have more questions otherwise feel free to close the issue!

**Comment by rrodriguezreche** [comment]
Hi @furkhat , thanks, you are right. I was actually running `zksync init`, but this was the message I was getting:

```
Checking environment
Node version 10 is supported
```

To make something useful out of this, I 'd request to be more explicit about these message and change it to `Unsupported version of node detected, please use version 10` or something along the line. I was reading the current ones just as regular debug, not errors, so I went ahead with the rest. I think it would be also helpful to specify the node version in https://github.com/matter-labs/zksync/blob/master/docs/setup-dev.md .

I will close the issue. Thank you again! :)
