### ISSUE TITLE
failed in zksync server

### ISSUE THREAD

**Issue by WillZhuang** [matter-labs/zksync#229]
my environment is:
```shell
➜  documents cat /proc/version
Linux version 5.3.0-45-generic (buildd@lcy01-amd64-027) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020
➜  documents uname -a
Linux elementaryos 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
➜  documents docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                              NAMES
fafe4a5c7415        adria0/tesseracts              "./tesseracts --cfg …"   5 hours ago         Up 5 hours          0.0.0.0:8000->8000/tcp                                             zksync_tesseracts_1
4c6f1caa9636        postgres:10.4                  "docker-entrypoint.s…"   5 hours ago         Up 5 hours          0.0.0.0:5432->5432/tcp                                             zksync_postgres_1
b39d0750d541        matterlabs/geth:latest         "sh /bin/geth-entry.…"   5 hours ago         Up 5 hours          8547/tcp, 0.0.0.0:8545-8546->8545-8546/tcp, 30303/tcp, 30303/udp   zksync_geth_1
23a19dea1bad        matterlabs/dev-ticker:latest   "dev-ticker-server"      5 hours ago         Up 5 hours          0.0.0.0:9876->9876/tcp                                             zksync_dev-ticker_1
```

When I run `zksync server` , it failed as below log. Seems something of openssl is wrong, can you kindly help?

```shell
➜  documents zksync env
 * dev
➜  documents zksync plonk-setup
Setup is fine
➜  documents zksync server
   Compiling openssl-sys v0.9.58
   Compiling pq-sys v0.4.6
error: failed to run custom build command for `openssl-sys v0.9.58`

Caused by:
  process didn't exit successfully: `/home/will/documents/zksync/target/release/build/openssl-sys-b6cefd4b366868af/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_DIR
OPENSSL_DIR unset
run pkg_config fail: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"`: No such file or directory (os error 2)"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

$HOST = x86_64-unknown-linux-gnu
$TARGET = x86_64-unknown-linux-gnu
openssl-sys = 0.9.58


It looks like you're compiling on Linux and also targeting Linux. Currently this
requires the `pkg-config` utility to find OpenSSL but unfortunately `pkg-config`
could not be found. If you have OpenSSL installed you can likely fix this by
installing `pkg-config`.

', /home/will/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.58/build/find_normal.rs:157:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: std::panicking::begin_panic
  12: build_script_main::find_normal::get_openssl
  13: build_script_main::main
  14: std::rt::lang_start::{{closure}}
  15: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  16: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  18: std::panicking::try
             at src/libstd/panicking.rs:281
  19: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  20: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  21: main
  22: __libc_start_main
  23: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
Makefile:124: recipe for target 'server' failed
make: *** [server] Error 101
```

**Comment by gluk64** [comment]
Hey @WillZhuang, it's best to chat quickly. Do you have telegram? Please ping me at @herrmit

Best,
Alex

**Comment by WillZhuang** [comment]
> Hey @WillZhuang, it's best to chat quickly. Do you have telegram? Please ping me at @herrmit
> 
> Best,
> Alex

I can login Telegram on iPhone only, because GFW China.
I can only send messages to mutual contacts, I added you already, can you add me @willzhuang?

**Comment by dvush** [comment]
What is your linux distro? It looks like you don't have `pkgconfig` installed.

Here is snippet that I use to prepare empty ubuntu machine for zksync testing:

```
apt update
apt install htop vim yarn nodejs docker docker-compose docker-compose jq postgresql-client-10 gcc libsqlite3-dev libpq-dev libmysqlclient-dev coreutils make openssl pkg-config axel -y
```

I think you can use this:
```
apt install postgresql-client-10 gcc libsqlite3-dev libpq-dev libmysqlclient-dev coreutils make openssl pkg-config axel
``

**Comment by WillZhuang** [comment]
I will test later. almost GFW. I close it here. Keep in focus on zksync.
