### ISSUE TITLE
Failed to init CoinGecko client - zk server crashing

### ISSUE THREAD

**Issue by junaidev** [matter-labs/zksync#248]
server error:

```   Finished release [optimized] target(s) in 0.20s
     Running `target/release/server`
[2020-09-25T06:19:36Z INFO  server::leader_election] No kubernetes detected, node is selected as leader
[2020-09-25T06:19:36Z INFO  server::leader_election] Node is selected as leader
[2020-09-25T06:19:36Z INFO  server::observer_mode] starting observer mode
[2020-09-25T06:19:36Z INFO  server::observer_mode] updated circuit tree to block: 0
[2020-09-25T06:19:36Z INFO  server::state_keeper] Loaded committed state: last block number: 0, unprocessed priority op: 0
[2020-09-25T06:19:36Z INFO  server::observer_mode] updated state keeper init params to block: 0
[2020-09-25T06:19:37Z DEBUG server] starting server
[2020-09-25T06:19:37Z INFO  server] starting actors
[2020-09-25T06:19:37Z INFO  server::state_keeper] created state keeper, root hash = Fr(0x29b5353c8f72f2050e597f25050c12653fe92c11997b79cb35cb3ac4644c20c6)
[2020-09-25T06:19:37Z INFO  server::state_keeper] Executed restored proposed block: 0 transactions, 0 priority operations, 0 failed transactions
[2020-09-25T06:19:37Z INFO  server::mempool] 0 transactions were restored from the persistent mempool storage
[2020-09-25T06:19:37Z INFO  server::prover_server] Starting witness generator (1,2)
[2020-09-25T06:19:37Z INFO  server::prover_server] Starting witness generator (2,2)
thread 'main' panicked at 'failed to init CoinGecko client: reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) }

   0: failure::backtrace::internal::InternalBacktrace::new
   1: failure::backtrace::Backtrace::new
   2: server::fee_ticker::ticker_api::coingecko::CoinGeckoAPI::new
   3: server::fee_ticker::run_ticker_task
   4: server::main::{{closure}}
   5: tokio::runtime::enter::Enter::block_on
   6: tokio::runtime::context::enter
   7: tokio::runtime::handle::Handle::enter
   8: server::main
   9: std::rt::lang_start::{{closure}}
  10: std::rt::lang_start_internal::{{closure}}
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:297
      std::panicking::try
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/rt.rs:51
```

**Comment by dvush** [comment]
You should do `zk init` to have all the dev servers started including ticker service that emulated COIN_GECKO api, but it seem that error is because you don't have required env variable.

**Comment by popzxc** [comment]
Closing as stale.
