### ISSUE TITLE
Integration Test Failure

### ISSUE THREAD

**Issue by NoCtrlZ** [matter-labs/zksync#273]
I am trying the integration test but some errors happened.
It says `should execute a withdrawal` and `should execute a ForcedExit` failed to resolve the promise so it can't be finished.
Do you know how to fix this error?
```
ubuntu@ip-x-x-x-x:~/zksync$ zk test i server
yarn run v1.22.5
$ yarn workspace ts-tests test
$ zk f mocha tests/main.test.ts


  ZkSync integration tests (token: ETH, transport: HTTP)
    ✓ should execute an auto-approved deposit (2344ms)
    ✓ should execute a normal deposit (1984ms)
    ✓ should change pubkey onchain (2142ms)
    ✓ should execute a transfer to new account (610ms)
    ✓ should execute a transfer to existing account (619ms)
    ✓ should execute a transfer to self (630ms)
    ✓ should change pubkey offchain (639ms)
    ✓ should test multi-transfers (1428ms)
    1) should execute a withdrawal
    2) should execute a ForcedExit
    ✓ should check collected fees (7ms)
    ✓ should fail trying to send tx with wrong signature (124ms)
    Full Exit tests
network block skew detected; skipping block events
      ✓ should execute full-exit on random wallet (2514ms)
      ✓ should fail full-exit with wrong eth-signer (3939ms)
      ✓ should execute a normal full-exit (2071ms)
      ✓ should execute full-exit on an empty wallet (1963ms)

  ZkSync integration tests (token: wBTC, transport: WS)
    ✓ should execute an auto-approved deposit (1954ms)
    ✓ should execute a normal deposit (5869ms)
    ✓ should change pubkey onchain (2153ms)
    ✓ should execute a transfer to new account (183ms)
    ✓ should execute a transfer to existing account (200ms)
    ✓ should execute a transfer to self (201ms)
    ✓ should change pubkey offchain (204ms)
    ✓ should test multi-transfers (998ms)
    3) should execute a withdrawal
    4) should execute a ForcedExit
    ✓ should check collected fees (10ms)
    ✓ should fail trying to send tx with wrong signature (200ms)
    Full Exit tests
network block skew detected; skipping block events
      ✓ should execute full-exit on random wallet (2130ms)
      ✓ should fail full-exit with wrong eth-signer (4043ms)
      ✓ should execute a normal full-exit (1995ms)
      ✓ should execute full-exit on an empty wallet (2166ms)


  28 passing (49m)
  4 failing

  1) ZkSync integration tests (token: ETH, transport: HTTP)
       should execute a withdrawal:
     Error: Timeout of 720000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ubuntu/zksync/core/tests/ts-tests/tests/main.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) ZkSync integration tests (token: ETH, transport: HTTP)
       should execute a ForcedExit:
     Error: Timeout of 720000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ubuntu/zksync/core/tests/ts-tests/tests/main.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  3) ZkSync integration tests (token: wBTC, transport: WS)
       should execute a withdrawal:
     Error: Timeout of 720000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ubuntu/zksync/core/tests/ts-tests/tests/main.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  4) ZkSync integration tests (token: wBTC, transport: WS)
       should execute a ForcedExit:
     Error: Timeout of 720000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/ubuntu/zksync/core/tests/ts-tests/tests/main.test.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)



error Command failed with exit code 4.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 4
Command: /usr/bin/node
Arguments: /usr/share/yarn/lib/cli.js test
Directory: /home/ubuntu/zksync/core/tests/ts-tests
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 4.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Child process exited with code 4
```

**Comment by NoCtrlZ** [comment]
成功したLoop Tx
```
[2021-01-23T11:50:45Z DEBUG zksync_eth_sender] witness_data for block 1: , [0]
[2021-01-23T11:50:45Z INFO  zksync_eth_sender::tx_queue] Adding commit operation to the queue. Sent pending txs count: 0, max pending txs count: 3, size of commit queue: 1
[2021-01-23T11:50:45Z INFO  zksync_eth_sender] Added ZKSync operation <id 1; action: COMMIT; block: 1> to queue
[2021-01-23T11:50:45Z INFO  zksync_eth_sender] transaction loop
[2021-01-23T11:50:45Z INFO  zksync_eth_sender] TxData { op_type: Commit, raw: [78, 145, 60, 217, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 22, 227, 114, 99, 94, 98, 116, 57, 120, 36, 189, 195, 235, 86, 255, 26, 57, 64, 28, 112, 217, 73, 98, 34, 219, 99, 221, 77, 168, 58, 112, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 14, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 108, 107, 147, 91, 139, 189, 64, 0, 0, 19, 155, 247, 30, 69, 28, 150, 84, 115, 245, 219, 127, 38, 227, 164, 95, 214, 244, 89, 208, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 1, 140, 125, 170, 85, 225, 181, 36, 83, 79, 105, 157, 113, 91, 219, 101, 46, 199, 206, 90, 158, 19, 155, 247, 30, 69, 28, 150, 84, 115, 245, 219, 127, 38, 227, 164, 95, 214, 244, 89, 208, 0, 0, 0, 0, 0, 0, 34, 107, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], operation: Some(Operation { id: Some(1), action: "COMMIT", block: Block { block_number: 1, new_root_hash: Fr(0x16e372635e6274397824bdc3eb56ff1a39401c70d9496222db63dd4da83a7031), fee_account: 0, block_transactions: [PriorityOp(ExecutedPriorityOp { priority_op: PriorityOp { serial_id: 0, data: Deposit(Deposit { from: 0x36615cf349d7f6344891b1e7ca7c72883f5dc049, token: 0, amount: BigUint { data: [3175088128, 1804819339, 108] }, to: 0x139bf71e451c965473f5db7f26e3a45fd6f459d0 }), deadline_block: 314045, eth_hash: [215, 79, 68, 112, 184, 54, 233, 249, 245, 109, 99, 157, 10, 30, 114, 132, 4, 194, 54, 79, 228, 126, 45, 136, 120, 164, 83, 251, 198, 157, 100, 142], eth_block: 296765 }, op: Deposit(DepositOp { priority_op: Deposit { from: 0x36615cf349d7f6344891b1e7ca7c72883f5dc049, token: 0, amount: BigUint { data: [3175088128, 1804819339, 108] }, to: 0x139bf71e451c965473f5db7f26e3a45fd6f459d0 }, account_id: 1 }), block_index: 0, created_at: 2021-01-23T11:50:42.380583Z }), Tx(ExecutedTx { signed_tx: SignedZkSyncTx { tx: ChangePubKey(ChangePubKey { account_id: 1, account: 0x139bf71e451c965473f5db7f26e3a45fd6f459d0, new_pk_hash: sync:8c7daa55e1b524534f699d715bdb652ec7ce5a9e, fee_token: 0, fee: BigUint { data: [3619371008, 6402] }, nonce: 0, signature: { pub_key: 510eecfe33fde7a2906a4a5d019a385fc17c54f6b028d1c52621aae6e8c1111a, sign: 509b266c203feeabf4e8b1f3246f6f6d5c18d09fdda13e8f01ee276ce8874c831ec8e66c27e1f1d334d1e25413a9f3ae61a909a16e1b5aceb9d44167236b7e02 }, eth_signature: None, cached_signer: NotCached }), eth_sign_data: None }, success: true, op: Some(ChangePubKeyOffchain(ChangePubKeyOp { tx: ChangePubKey { account_id: 1, account: 0x139bf71e451c965473f5db7f26e3a45fd6f459d0, new_pk_hash: sync:8c7daa55e1b524534f699d715bdb652ec7ce5a9e, fee_token: 0, fee: BigUint { data: [3619371008, 6402] }, nonce: 0, signature: { pub_key: 510eecfe33fde7a2906a4a5d019a385fc17c54f6b028d1c52621aae6e8c1111a, sign: 509b266c203feeabf4e8b1f3246f6f6d5c18d09fdda13e8f01ee276ce8874c831ec8e66c27e1f1d334d1e25413a9f3ae61a909a16e1b5aceb9d44167236b7e02 }, eth_signature: None, cached_signer: NotCached }, account_id: 1 })), fail_reason: None, block_index: Some(1), created_at: 2021-01-23T11:50:44.391900Z, batch_id: None })], processed_priority_ops: (0, 1), block_chunks_size: 30, commit_gas_limit: 408623, verify_gas_limit: 1300000 } }) }
[2021-01-23T11:50:46Z INFO  zksync_witness_generator] Sent prover_data for block 1
[2021-01-23T11:50:46Z INFO  zksync_eth_sender] Gas limit for <ETH Operation id: 1> is 408623
```

**Comment by popzxc** [comment]
I guess you are using real prover (`zk prover`). It requires a powerful machine to compute zero knowledge proofs, and even on a powerful machine this operation consumes a decent amount of time.

Integration tests were written to test the server logic, thus they expect one to use "dummy prover" which doesn't perform actual computations.

Info on how to use dummy prover could be found [here](https://github.com/matter-labs/zksync/blob/master/docs/development.md#using-dummy-prover).

**Comment by NoCtrlZ** [comment]
Exactly.
Thank you.
It was my fault.
