### ISSUE TITLE
Prover Container Doesn't Work

### ISSUE THREAD

**Issue by NoCtrlZ** [matter-labs/zksync#274]
In following Dockerfile, the prover application doesn't work because of `localhost:8088 connection refused`.
How can I fix this error?
Do you have any idea about this?
https://github.com/matter-labs/zksync/blob/master/docker/prover/Dockerfile
```
# plonk_step_by_step_prover "hostname" 2>&1
[2021-01-01T08:54:54Z INFO  zksync_prover::cli_utils] creating prover, worker name: hostname
[2021-01-01T08:54:54Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:54:54Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 1.4s
[2021-01-01T08:54:56Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:54:56Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 2.2s
[2021-01-01T08:54:58Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:54:58Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 2.6s
[2021-01-01T08:55:00Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:55:00Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 2.5s
[2021-01-01T08:55:03Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:55:03Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 4.6s
[2021-01-01T08:55:08Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:55:08Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 5.1s
[2021-01-01T08:55:13Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:55:13Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 11.3s
[2021-01-01T08:55:24Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:55:24Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 11.1s
[2021-01-01T08:55:35Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:55:35Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 14.6s
[2021-01-01T08:55:50Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:55:50Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 14.3s
[2021-01-01T08:56:04Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:56:04Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 5.7s
[2021-01-01T08:56:10Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:56:10Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 6.7s
[2021-01-01T08:56:16Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:56:16Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 15.0s
[2021-01-01T08:56:31Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:56:31Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 8.0s
[2021-01-01T08:56:39Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:56:39Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 5.9s
[2021-01-01T08:56:45Z INFO  zksync_prover::client] Registering prover...
[2021-01-01T08:56:45Z WARN  zksync_prover::client] Failed to reach server err: <register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)>, retrying after: 14.6s
[2021-01-01T08:57:00Z INFO  zksync_prover::client] Registering prover...
thread 'main' panicked at 'Prover can't reach server, for the max elapsed time of the backoff: register request failed: error sending request for url (http://127.0.0.1:8088/register): error trying to connect: tcp connect error: Connection refused (os error 111)', core/bin/prover/src/client.rs:90:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:342
  13: zksync_prover::client::ApiClient::with_retries::{{closure}}
  14: zksync_prover::client::ApiClient::register_prover
  15: zksync_prover::cli_utils::main_for_prover_impl
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  19: std::panicking::try
             at src/libstd/panicking.rs:274
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  22: main
  23: __libc_start_main
  24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Thank you!

**Comment by NoCtrlZ** [comment]
I think the prover server is working on the operator server so this is just my misstakeing.
