### ISSUE TITLE
Cannot read property 'Interface' of undefined

### ISSUE THREAD

**Issue by LonYui** [matter-labs/zksync#433]
exports.IERC20_INTERFACE = new ethers_1.utils.Interface(require('../abi/IERC20.json').abi);
                                              ^

TypeError: Cannot read property 'Interface' of undefined
    at Object.<anonymous> (/Users/k/wizard/node_modules/zksync/build/utils.js:23:47)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/k/wizard/node_modules/zksync/build/eth-message-signer.js:33:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Comment by MaxSpiro** [comment]
same issue

**Comment by LonYui** [comment]
我後來使用ether.js完成我的功能 ，完全沒有用到此模組。

**Comment by lewilewilewi** [comment]
Your version of ethers.js is too new - ethers.utils has been removed in recent versions
