### ISSUE TITLE
Probably an issue with ethers

### ISSUE THREAD

**Issue by zakopane262** [matter-labs/zksync#480]
I am using ethers 3.0.9 and getting this error

exports.IERC20_INTERFACE = new ethers_1.utils.Interface(require('../abi/IERC20.json').abi);

TypeError: Cannot read property 'Interface' of undefined
at Object. (/Users/k/wizard/node_modules/zksync/build/utils.js:23:47)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:101:18)
at Object. (/Users/k/wizard/node_modules/zksync/build/eth-message-signer.js:33:17)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Comment by Seuncoded** [comment]
Is the error persit
