### ISSUE TITLE
Error: invalid value for value.sealFields (Not an array!) 

### ISSUE THREAD

**Issue by haerker** [matter-labs/zksync#611]
When I run the example of L1 and L2 communication provided on the official website, the contracts are successfully deployed to both L1 and L2. However, when I call increment-counter.ts, 
`yarn ts-node ./scripts/increment-counter.ts`
I encounter errors of incorrect types.

When I set up my local private chain with Buse as L1, the following error occurs:
```
Error: invalid value for value.sealFields (Not an array!) (value={ "difficulty": "0x1", "extraData": "0xf90148a00000000000000000000000000000000000000000000000000000000000000000f854940ad4ca90ea2e6befadc49a9cb0f4f7d1045e73b4944a4ce383d932f8033d996e3c23b4dd605bcdb2dd946998aeb210210e4908af27da18eb0bae9a176ac9947c34ad2255cb746b59b19339a0e9bb1a97867b99808400000000f8c9b84166b3987f1c571fe58c1730a76b2174cec1c709c09454efda0e2db3aeca0aed06581c00c8e5750b6bb58e95858da4cf4df05dc1d49538e2b47255dc21247d1d9f00b841c1a9e65e4a9b0160ae1d108c33c3313f426b0818c58d87093475acebe2522483560ff19de794d0583d5807287ebfd095cd72a0e692a57fbe61fd9707515f903f01b841ff1dae6675037ef736cbbff15e3764513b74bc85a7cf0b3b76d63179880c9da97e56473739f05abf80df7e15ded8db20183442df7f11e5e1340d6016674405c300", "gasLimit": "0x47b760", "gasUsed": "0x0", "hash": "0xa05952ce75637bd87aebefd21ec4df0fc92543f92ceadc8cbf21e02a91e60d17", "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner": "0x7c34ad2255cb746b59b19339a0e9bb1a97867b99", "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365", "nonce": "0x0000000000000000", "number": "0x2425", "parentHash": "0x399c1038ecd98909436bf7ebe37f773d226e99f5c158d59de477898f49163c01", "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size": "0x34b", "stateRoot": "0xaea23e7deacd0256dacda29827b2103830f9366a69129cc6f7a01cc423b4bcf3", "timestamp": "0x66081bbe", "totalDifficulty": "0x2426", "transactions": [  ], "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", "uncles": [  ] }, code=BAD_DATA, version=6.11.1)
    at makeError (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/ethers/src.ts/utils/errors.ts:694:21)
    at assert (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/ethers/src.ts/utils/errors.ts:715:25)
    at /home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/zksync-ethers/src/format.ts:72:15
    at formatBlock (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/zksync-ethers/src/format.ts:174:18)
    at Provider._wrapBlock (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/zksync-ethers/src/provider.ts:110:35)
    at getFeeDataFunc (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/ethers/src.ts/providers/abstract-provider.ts:935:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Provider.getFeeData (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/ethers/src.ts/providers/abstract-provider.ts:952:16)
    at async Provider.getGasPrice (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/zksync-ethers/src/provider.ts:302:23)
    at async main (/home/haerker/zksync/cross-chain-tutorial/L2-counter/scripts/increment-counter.ts:39:20) {
  code: 'BAD_DATA',
  value: {
    number: '0x2425',
    hash: '0xa05952ce75637bd87aebefd21ec4df0fc92543f92ceadc8cbf21e02a91e60d17',
    mixHash: '0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365',
    parentHash: '0x399c1038ecd98909436bf7ebe37f773d226e99f5c158d59de477898f49163c01',
    nonce: '0x0000000000000000',
    sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    transactionsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
    stateRoot: '0xaea23e7deacd0256dacda29827b2103830f9366a69129cc6f7a01cc423b4bcf3',
    receiptsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
    miner: '0x7c34ad2255cb746b59b19339a0e9bb1a97867b99',
    difficulty: '0x1',
    totalDifficulty: '0x2426',
    extraData: '0xf90148a00000000000000000000000000000000000000000000000000000000000000000f854940ad4ca90ea2e6befadc49a9cb0f4f7d1045e73b4944a4ce383d932f8033d996e3c23b4dd605bcdb2dd946998aeb210210e4908af27da18eb0bae9a176ac9947c34ad2255cb746b59b19339a0e9bb1a97867b99808400000000f8c9b84166b3987f1c571fe58c1730a76b2174cec1c709c09454efda0e2db3aeca0aed06581c00c8e5750b6bb58e95858da4cf4df05dc1d49538e2b47255dc21247d1d9f00b841c1a9e65e4a9b0160ae1d108c33c3313f426b0818c58d87093475acebe2522483560ff19de794d0583d5807287ebfd095cd72a0e692a57fbe61fd9707515f903f01b841ff1dae6675037ef736cbbff15e3764513b74bc85a7cf0b3b76d63179880c9da97e56473739f05abf80df7e15ded8db20183442df7f11e5e1340d6016674405c300',
    size: '0x34b',
    gasLimit: '0x47b760',
    gasUsed: '0x0',
    timestamp: '0x66081bbe',
    uncles: [],
    transactions: []
  },
  shortMessage: 'invalid value for value.sealFields (Not an array!)'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When my L1 is provided by sepolia on the official website, the following error occurs:

```
Error: invalid value for value.sealFields (Not an array!) (value={ "baseFeePerGas": "0x52a1120", "blobGasUsed": "0xc0000", "difficulty": "0x0", "excessBlobGas": "0x4d80000", "extraData": "0x62303930386665", "gasLimit": "0x1c9c380", "gasUsed": "0x4454d1", "hash": "0x39d13bd2ece88073af6e6396e873320370223e0f9e3268637dbb4fbac66d76f0", "logsBloom": "0x841800088808408800524a2219100200000110000020804202024002c08b800421400008208400002820004000040180208000040620800016393c0102e42410002090880e1400004116204b0128080d0420300381862168300a804040800021088000028a0140502042040002000b00410b20c8095802a40008001c824808008e4208848322c02064c0252000a04490303a0820494c412010818008040020406208420a9827408004000000000084840252000320000108048002221c0004004004510203000a00000104111b12000420a00210020000052401190500056200003600042520200800c620022000000c0048800048380012010092000d085204", "miner": "0x0c06b6d4ec451987e8c0b772ffcf7f080c46447a", "mixHash": "0x3cc8a81c786af0e388697ca9c012a1d534f3a28e192d0c2f161074d979a1e3c7", "nonce": "0x0000000000000000", "number": "0x555530", "parentBeaconBlockRoot": "0xf9335000d4be6e4335d7b2d4e302bb80148bfb1f519ce05fce5154f9cd362ec7", "parentHash": "0xc1b6728cab7abb65e234a77acc7d820eba83209049543630bad7c185b1d3846b", "receiptsRoot": "0xe1dcee3d4e3e099de316082765abd75d08e345ebd56b0da637ff5044ad0e6952", "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size": "0xeb12", "stateRoot": "0x2e6b121953c83019da8129148b5fd3a2930516e5029e80e8b6d21c2c3be12bc0", "timestamp": "0x66082128", "totalDifficulty": "0x3c656d23029ab0", "transactions": [ "0x4fb48d5354c81e018ed82a39162eb6aa04b650013e93759b5f439777052b18aa", "0xc65ecb2b6e6b23855a4fa826b5921788b83eddb76bea8ecf5419e108dead3c8c", "0x1e6a936d3f4c8066d99e7d53ff68258d2ffa8992fb89b72fbfd3950298de5028", "0xa85480cb9275adb9d56e4f3216779c8fa16af3f3511728ffa08889a31b22a31e", "0x570f61b046fcc539a96cfa5f14298965a2dd5e6d15493c5f350c469884a5bd8d", "0xb3dbe519b55e8a0e926a4983e8e9b326342627c4e9fe0683ee5d2961977c4efd", "0x7070e23fe93d7b632d5cbfc2e212717e4dc5c080859b8e914aac551d7699793d", "0xbdca04c35ab5a212b163bc8596800fb83ce34fab601de163d62913f5db684100", "0x0fb34ccb171f19521f61d65a3b95fc8da0c2e38e6b6559d994c6aba8af5fe22b", "0xe3e60786981d2ac98f4ca992216aee1f95f86f3f756e37e41f9b4cadd5e1d0a5", "0x4edd9be086573df0f159c00a936cb5b13f48162f0cb603577daccde5eaab301c", "0x93a366dd8bdeb6e9004bcc2c3acc407d2585c8295025884af8aee27a2469323a", "0xb4467c99ea51e10c049a95bb787d10a8a715ab1452c2a50320a53dc95bd80d3a", "0x9ea61c806c1b469634ae6af54a406e829eb7be651b9b0cc4e5c034613527eac8", "0x0e9b1282aafbd6f49baf2a397a86386fa02371ba0fdebb6a609db3434528b8fa", "0x229d18c3702f5a8c0838eb94281d99799dbba74f911d8298fab24ca6bc48287c", "0x0e3b9d159d9b9e2593f4486a22d2d07ed63d2fcf638b4ae85fdab81f7c3fbf5a", "0x3ae38abb497631b3007c8e31690e42ce04fe7837192b4241dc2dad1c96df381d", "0xaad8b2b0d49c836bd097f8816f94f03d925507b6e04da5de77eaa28d0dd60129", "0x06424c16c5fbd77f6d06aff5b061de69ffd171f480bffb3c34102fe6e7e10a79", "0x33bdab1ac8894a3679cbfc2defcfc931c9630452bcbba251dccbfb270602ec24", "0x90ac3c48f08f4fbd8e0fdca2e9e956d2b6ef52d308a060b9fc745bb325186677", "0x40384f24c82fc429a44dc1b4e172af0d83259d95d5f097e5f603b5bfa1623410", "0xe912a274eca5ea1e68088b5ca20e7df9cfe95c0a1a2620fc7730f69ffce275f2", "0xce6e64f33fce7ce259e94e8df5d755031d3f1c7a21e33cd1b7048fb80daca4f6", "0x90018481299dc6486596b22d1f767f3e61d7a9f1ccde17bcda23c22e424bafba", "0x2822d5ee90f151d49cfd064c8c2b31b80987398e81c1cb142fcf83c295e1d466", "0x851910628b81acf8a505eb413e80b318527e04ea39219d3f38ad89460b83805b", "0x6a8be4e49f47e3d069f18408d4f1c602e30376267e2d80a0e29f1467d897bdcb", "0x148c3d15c11dead58a515f72b1bd25900e6356043cb5f307aa0d95bcee0826f4", "0x170853da85265d475a851549b5cc896b1941c0800f56ef37cec40104d6e20a40", "0x967250ad99a16270146e383462e794f7931294363912089bfaa041fc5dfb3cf0" ], "transactionsRoot": "0xef73f4106a60fce0962863708685b8f6df3172478da6aefce89c2c82cbe33dca", "uncles": [  ], "withdrawals": [ { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x38578", "index": "0x27b0227", "validatorIndex": "0x1bf" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x367f8", "index": "0x27b0228", "validatorIndex": "0x1c0" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x367f8", "index": "0x27b0229", "validatorIndex": "0x1c1" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x38578", "index": "0x27b022a", "validatorIndex": "0x1c2" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x38578", "index": "0x27b022b", "validatorIndex": "0x1c3" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x367f8", "index": "0x27b022c", "validatorIndex": "0x1c4" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x367f8", "index": "0x27b022d", "validatorIndex": "0x1c5" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x367f8", "index": "0x27b022e", "validatorIndex": "0x1c6" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x367f8", "index": "0x27b022f", "validatorIndex": "0x1c7" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x38578", "index": "0x27b0230", "validatorIndex": "0x1c8" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x367f8", "index": "0x27b0231", "validatorIndex": "0x1c9" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x367f8", "index": "0x27b0232", "validatorIndex": "0x1ca" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x367f8", "index": "0x27b0233", "validatorIndex": "0x1cb" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x367f8", "index": "0x27b0234", "validatorIndex": "0x1cc" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x367f8", "index": "0x27b0235", "validatorIndex": "0x1cd" }, { "address": "0x25c4a76e7d118705e7ea2e9b7d8c59930d8acd3b", "amount": "0x367f8", "index": "0x27b0236", "validatorIndex": "0x1ce" } ], "withdrawalsRoot": "0xcc740b49b10192bf5b5b7d9909f3f8250dfe730a3587c445210bfdb8506ae91f" }, code=BAD_DATA, version=6.11.1)
    at makeError (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/ethers/src.ts/utils/errors.ts:694:21)
    at assert (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/ethers/src.ts/utils/errors.ts:715:25)
    at /home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/zksync-ethers/src/format.ts:72:15
    at formatBlock (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/zksync-ethers/src/format.ts:174:18)
    at Provider._wrapBlock (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/zksync-ethers/src/provider.ts:110:35)
    at getFeeDataFunc (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/ethers/src.ts/providers/abstract-provider.ts:935:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Provider.getFeeData (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/ethers/src.ts/providers/abstract-provider.ts:952:16)
    at async Provider.getGasPrice (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/zksync-ethers/src/provider.ts:302:23)
    at async main (/home/haerker/zksync/cross-chain-tutorial/L2-counter/scripts/increment-counter.ts:38:20) {
  code: 'BAD_DATA',
  value: {
    baseFeePerGas: '0x52a1120',
    blobGasUsed: '0xc0000',
    difficulty: '0x0',
    excessBlobGas: '0x4d80000',
    extraData: '0x62303930386665',
    gasLimit: '0x1c9c380',
    gasUsed: '0x4454d1',
    hash: '0x39d13bd2ece88073af6e6396e873320370223e0f9e3268637dbb4fbac66d76f0',
    logsBloom: '0x841800088808408800524a2219100200000110000020804202024002c08b800421400008208400002820004000040180208000040620800016393c0102e42410002090880e1400004116204b0128080d0420300381862168300a804040800021088000028a0140502042040002000b00410b20c8095802a40008001c824808008e4208848322c02064c0252000a04490303a0820494c412010818008040020406208420a9827408004000000000084840252000320000108048002221c0004004004510203000a00000104111b12000420a00210020000052401190500056200003600042520200800c620022000000c0048800048380012010092000d085204',
    miner: '0x0c06b6d4ec451987e8c0b772ffcf7f080c46447a',
    mixHash: '0x3cc8a81c786af0e388697ca9c012a1d534f3a28e192d0c2f161074d979a1e3c7',
    nonce: '0x0000000000000000',
    number: '0x555530',
    parentBeaconBlockRoot: '0xf9335000d4be6e4335d7b2d4e302bb80148bfb1f519ce05fce5154f9cd362ec7',
    parentHash: '0xc1b6728cab7abb65e234a77acc7d820eba83209049543630bad7c185b1d3846b',
    receiptsRoot: '0xe1dcee3d4e3e099de316082765abd75d08e345ebd56b0da637ff5044ad0e6952',
    sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
    size: '0xeb12',
    stateRoot: '0x2e6b121953c83019da8129148b5fd3a2930516e5029e80e8b6d21c2c3be12bc0',
    timestamp: '0x66082128',
    totalDifficulty: '0x3c656d23029ab0',
    transactions: [
      '0x4fb48d5354c81e018ed82a39162eb6aa04b650013e93759b5f439777052b18aa',
      '0xc65ecb2b6e6b23855a4fa826b5921788b83eddb76bea8ecf5419e108dead3c8c',
      '0x1e6a936d3f4c8066d99e7d53ff68258d2ffa8992fb89b72fbfd3950298de5028',
      '0xa85480cb9275adb9d56e4f3216779c8fa16af3f3511728ffa08889a31b22a31e',
      '0x570f61b046fcc539a96cfa5f14298965a2dd5e6d15493c5f350c469884a5bd8d',
      '0xb3dbe519b55e8a0e926a4983e8e9b326342627c4e9fe0683ee5d2961977c4efd',
      '0x7070e23fe93d7b632d5cbfc2e212717e4dc5c080859b8e914aac551d7699793d',
      '0xbdca04c35ab5a212b163bc8596800fb83ce34fab601de163d62913f5db684100',
      '0x0fb34ccb171f19521f61d65a3b95fc8da0c2e38e6b6559d994c6aba8af5fe22b',
      '0xe3e60786981d2ac98f4ca992216aee1f95f86f3f756e37e41f9b4cadd5e1d0a5',
      '0x4edd9be086573df0f159c00a936cb5b13f48162f0cb603577daccde5eaab301c',
      '0x93a366dd8bdeb6e9004bcc2c3acc407d2585c8295025884af8aee27a2469323a',
      '0xb4467c99ea51e10c049a95bb787d10a8a715ab1452c2a50320a53dc95bd80d3a',
      '0x9ea61c806c1b469634ae6af54a406e829eb7be651b9b0cc4e5c034613527eac8',
      '0x0e9b1282aafbd6f49baf2a397a86386fa02371ba0fdebb6a609db3434528b8fa',
      '0x229d18c3702f5a8c0838eb94281d99799dbba74f911d8298fab24ca6bc48287c',
      '0x0e3b9d159d9b9e2593f4486a22d2d07ed63d2fcf638b4ae85fdab81f7c3fbf5a',
      '0x3ae38abb497631b3007c8e31690e42ce04fe7837192b4241dc2dad1c96df381d',
      '0xaad8b2b0d49c836bd097f8816f94f03d925507b6e04da5de77eaa28d0dd60129',
      '0x06424c16c5fbd77f6d06aff5b061de69ffd171f480bffb3c34102fe6e7e10a79',
      '0x33bdab1ac8894a3679cbfc2defcfc931c9630452bcbba251dccbfb270602ec24',
      '0x90ac3c48f08f4fbd8e0fdca2e9e956d2b6ef52d308a060b9fc745bb325186677',
      '0x40384f24c82fc429a44dc1b4e172af0d83259d95d5f097e5f603b5bfa1623410',
      '0xe912a274eca5ea1e68088b5ca20e7df9cfe95c0a1a2620fc7730f69ffce275f2',
      '0xce6e64f33fce7ce259e94e8df5d755031d3f1c7a21e33cd1b7048fb80daca4f6',
      '0x90018481299dc6486596b22d1f767f3e61d7a9f1ccde17bcda23c22e424bafba',
      '0x2822d5ee90f151d49cfd064c8c2b31b80987398e81c1cb142fcf83c295e1d466',
      '0x851910628b81acf8a505eb413e80b318527e04ea39219d3f38ad89460b83805b',
      '0x6a8be4e49f47e3d069f18408d4f1c602e30376267e2d80a0e29f1467d897bdcb',
      '0x148c3d15c11dead58a515f72b1bd25900e6356043cb5f307aa0d95bcee0826f4',
      '0x170853da85265d475a851549b5cc896b1941c0800f56ef37cec40104d6e20a40',
      '0x967250ad99a16270146e383462e794f7931294363912089bfaa041fc5dfb3cf0'
    ],
    transactionsRoot: '0xef73f4106a60fce0962863708685b8f6df3172478da6aefce89c2c82cbe33dca',
    uncles: [],
    withdrawals: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    withdrawalsRoot: '0xcc740b49b10192bf5b5b7d9909f3f8250dfe730a3587c445210bfdb8506ae91f'
  },
  shortMessage: 'invalid value for value.sealFields (Not an array!)'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nathanlwb** [comment]
Possible Reasons Why Things Aren't Working

Your Blockchain Setup Needs Tweaking:

Homemade Blockchain: If your blockchain isn't the standard Ethereum kind, double-check that it has all the 'parts' that Ethereum expects (especially something called "sealFields").
Official Test Network: If you're using a standard setup like Sepolia, make sure your code is using the right settings for that particular network.
Software Issues:

Out-of-sync Tools: Make sure your 'ethers.js' library (and 'zksync-ethers') plays nicely with your blockchain setup. Look for newer versions that might work better.
Handle Unexpected Data: If you can edit your code, consider adding bits to deal with weird "sealFields", just in case that's the problem.

**Comment by nursie999** [comment]
great
......

**Comment by tgmp117** [comment]
somewhat took me some time to understand but Great :)

**Comment by drawknife** [comment]
udpaded my library too. now some problems are solved
